#!/bin/bash

echo "🏦 SmartBank - Quick Start for Hackathon"
echo "========================================="
echo ""
echo "This script will:"
echo "1. Start all services (Database, Backend, Frontend, pgAdmin)"
echo "2. Create test data for demo"
echo "3. Show you all access points"
echo ""
read -p "Press Enter to continue..."

# Start services
echo ""
echo "🚀 Starting services..."
docker-compose up -d --build

echo ""
echo "⏳ Waiting for services to initialize (30 seconds)..."
sleep 30

# Check if backend is ready
echo ""
echo "🔍 Checking if backend is ready..."
until curl -s http://localhost:8000 > /dev/null 2>&1; do
    echo "   Waiting for backend..."
    sleep 5
done

echo "✅ Backend is ready!"

# Create test data
echo ""
echo "📊 Creating test data..."
docker-compose exec -T backend python create_test_data.py

echo ""
echo "========================================="
echo "✅ SmartBank is Ready!"
echo "========================================="
echo ""
echo "🌐 Access Points:"
echo ""
echo "   Frontend (Main App): http://localhost:3000"
echo "   ├─ Use this for your demo"
echo "   └─ Login with credentials below"
echo ""
echo "   Backend API: http://localhost:8000"
echo "   ├─ Direct API access"
echo "   └─ Use for Postman/cURL testing"
echo ""
echo "   API Documentation: http://localhost:8000/docs"
echo "   ├─ Interactive Swagger UI"
echo "   └─ Test all endpoints here"
echo ""
echo "   pgAdmin: http://localhost:5050"
echo "   ├─ Database management"
echo "   └─ Login: admin@smartbank.com / admin"
echo ""
echo "========================================="
echo "🔑 Demo Accounts:"
echo "========================================="
echo ""
echo "Admin Account:"
echo "   Email: admin@smartbank.com"
echo "   Password: admin123"
echo "   Features: Approve loans, view flagged transactions"
echo ""
echo "Auditor Account:"
echo "   Email: auditor@smartbank.com"
echo "   Password: auditor123"
echo "   Features: View audit logs"
echo ""
echo "Customer Accounts:"
echo "   1. john@example.com / password123"
echo "   2. jane@example.com / password123"
echo "   3. bob@example.com / password123"
echo "   Features: Create accounts, transfer, apply loans"
echo ""
echo "========================================="
echo "💡 Quick Demo Steps:"
echo "========================================="
echo ""
echo "1. Open http://localhost:3000"
echo ""
echo "2. Login as Customer (john@example.com / password123)"
echo "   - View dashboard"
echo "   - Check existing accounts"
echo "   - Make a transfer"
echo ""
echo "3. Try Fraud Detection:"
echo "   - Transfer a very large amount (₹100,000+)"
echo "   - Transaction will be flagged"
echo ""
echo "4. Apply for Loan:"
echo "   - Go to Loans tab"
echo "   - Apply for ₹500,000 for 60 months"
echo "   - See EMI calculation"
echo ""
echo "5. Login as Admin:"
echo "   - Logout and login as admin"
echo "   - View pending loans"
echo "   - Approve/reject loans"
echo "   - View flagged transactions"
echo ""
echo "6. Show pgAdmin:"
echo "   - Open http://localhost:5050"
echo "   - Login with admin credentials"
echo "   - Connect to database (postgres/5432)"
echo "   - Show table structure"
echo ""
echo "========================================="
echo "📚 Additional Resources:"
echo "========================================="
echo ""
echo "View Logs:"
echo "   docker-compose logs -f"
echo ""
echo "Stop Everything:"
echo "   docker-compose down"
echo ""
echo "Restart Services:"
echo "   docker-compose restart"
echo ""
echo "Clean Restart (removes all data):"
echo "   docker-compose down -v && docker-compose up -d"
echo ""
echo "========================================="
echo "🎉 Ready for your hackathon presentation!"
echo "========================================="
echo ""
